name: James McGrillis Photography
favicon: null
layout_spectrum: 0.835440582362935
typography_spectrum: 0.10703743598423898
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9034461944829673
  lightness: 0.6324977264739573
  saturation: 0.7794146903324872
  rhythmicContrast: 0.21991336159408092
purpose: []
